### ISSUE TITLE
can't use in .net4.8 

### ISSUE THREAD

**Issue by asine** [vitkuz573/PrismCommands.Fody#6]
## when use in .net 4.8 will report error:
Fody: Unable to find type 'System.Runtime.CompilerServices.CompilerGeneratedAttribute' in assembly 'System.Runtime'

- OS: windows 11 [e.g. Windows 10, macOS 12.0.1, Ubuntu 20.04]
- Platform: .net framework 4.8 [e.g. .NET Framework 4.8, .NET Core 3.1, .NET 5]
- PrismCommands.Fody Version:2.0.6 [e.g. 1.0.0]

- [ ] I have searched the existing issues to ensure that this issue has not already been reported.
- [ ] I have provided a clear and concise description of the issue, including any error messages, screenshots, or logs that may be relevant.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have provided information about my environment that may be relevant to the issue.
- [ ] I have provided any additional information that may be helpful in resolving the bug.
- [ ] I have reviewed my issue for accuracy and completeness.

**Comment by vitkuz573** [comment]
@asine I think I fixed it in the last commit. Please check

**Comment by asine** [comment]
[BlankApp2.zip](https://github.com/vitkuz573/PrismCommands.Fody/files/11611352/BlankApp2.zip)

**Comment by asine** [comment]
@vitkuz573 thanks,2.0.7 is ok.

**Comment by vitkuz573** [comment]
The release is out!
